language: python
python:
    - "2.7"
install:
    - pip install docutils --user
script:
    - find . -name \*.rst -exec rst2html.py {} 1>/dev/null 2>>warnings.log \;
    - if [[ -s warnings.log ]];then exit 1;fi
